= Getting Started with the Voltron Connection API
Gary Keim
v0.1, {docdatetime}

:sourcedir: ../../test/java

== Establishing a Connection

Relatively straightforward. There’ll be a simple service discovery mechanism with
connections happening through a ConnectionFactory:

[source,java,indent=0]
----
include::{sourcedir}/org/terracotta/connection/BasicConnectTest.java[tags=connect]
----

Properties could be passed through to the connection implementation. This is an
actual properties object instead of pulling out properties from the URI query
string because we need to pass through things like classloaders apparently…

== Creating an Entity

[source,java,indent=0]
----
include::{sourcedir}/org/terracotta/connection/BasicConnectTest.java[tags=create]
----

== Using an Entity

You might want to actually use a created and maintained entity, here’s how you might do it.

[source,java,indent=0]
----
include::{sourcedir}/org/terracotta/connection/BasicConnectTest.java[tags=using]
----

== Destroying an Entity

[source,java,indent=0]
----
include::{sourcedir}/org/terracotta/connection/BasicConnectTest.java[tags=destroy]
----

== API Reference

link:./apidocs/index.html[Overview]

link:./apidocs/org/terracotta/connection/Connection.html[org.terracotta.connection.Connection] +
link:./apidocs/org/terracotta/connection/ConnectionException.html[org.terracotta.connection.ConnectionException] +
link:./apidocs/org/terracotta/connection/ConnectionFactory.html[org.terracotta.connection.ConnectionFactory] +
link:./apidocs/org/terracotta/connection/ConnectionService.html[org.terracotta.connection.ConnectionService] +

link:./apidocs/org/terracotta/connection/entity/Entity.html[org.terracotta.connection.entity.Entity] +
link:./apidocs/org/terracotta/connection/entity/EntityRef.html[org.terracotta.connection.entity.EntityRef] +
